### ISSUE TITLE
Bug with updating Meteor.users

### ISSUE THREAD

**Issue by msavin** [msavin/Mongol#15]
It automatically signs out on the update. Maybe its because of the namespace?

**Comment by JackAdams** [comment]
#17 fixes this.  In my experiments, I think it's because updates were overwriting the `services` field (which is not published) with client side data that had no `services` field.  I wrote a little diffing algorithm to preserve unpublished fields and applied it to all updates, including Meteor.users.

**Comment by msavin** [comment]
Nice man, thanks for knocking that one out!
