### ISSUE TITLE
Collection can't be found : "Uncaught TypeError: Cannot read property 'find' of undefined"

### ISSUE THREAD

**Issue by parhelium** [msavin/Mongol#2]
First of all thank you for this great package!
## Issue:

Package cannot find collection if name of collection is not equal to the name of holding variable.
Example:

```
// doesn't work
Collection = {};
Collection.a = new Meteor.Collection( 'a'); 

// OR 

// doesn't work
A = new Meteor.Collection( 'a'); 

// will work
A = new Meteor.Collection( 'A');
a  = new Meteor.Collection( 'a');
```

I assume that you are trying to find collection by name using  : window[name]

There is package which can help to find the collection by name:
https://github.com/dburles/mongo-collection-instances/

Hopefully it should solve the problem :
Mongo.Collection.get('name)

**Comment by msavin** [comment]
It sounds like you're listing the collection name instead of the variable. Let me know if you're having issues despite that. 

Re auto-detection: we did that with MongoInspector but people had issues when the package wasn't listed first on the package list. Definitely going to look into how we can get this working in the long term.
