### ISSUE TITLE
Mongol doesn't see all the documents in all my collections.

### ISSUE THREAD

**Issue by dbhandel** [msavin/Mongol#41]
For instance. I have two users and it own sees one. I have another collection that shows zero documents even thought it has documents which can be found using meteor mongo in the terminal. 

I probably misunderstood the instructions after you upgraded to automatic recognition of collections. I set the Session.Mongol object to undefined to undo ny original Session settings. I have tried to remove and re-add Mongo several times without a solution. So, in summary, Mongol sees all my collections but not all my documents. Two of the collections that it began to see after I set Session.Mongol to undefined do not see new documents when they are added.

**Comment by JackAdams** [comment]
You'll only see the documents that have been published to the client.  It a feature, not a bug ... really. :-)
If you want to see all documents in your db, you'll need to publish everything.  Mongol doesn't set up publications and subscriptions (by design) -- it means that as you browse around your app and subscriptions change, you can see how the content of your client side collections changes.

**Comment by dbhandel** [comment]
Ahh! Makes sense. Thanks @JackAdams.
