### ISSUE TITLE
Mongol doesn't play nicely with GroundDB

### ISSUE THREAD

**Issue by alexiri** [msavin/Mongol#48]
Trying to add mongol to an app with GroundDB results in an error:

```
W20150309-18:20:14.048(1)? (STDERR)           
W20150309-18:20:14.050(1)? (STDERR) /home/alex/.meteor/packages/meteor-tool/.1.0.41.yumiah++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150309-18:20:14.051(1)? (STDERR)                                             throw(ex);
W20150309-18:20:14.051(1)? (STDERR)                                                   ^
W20150309-18:20:14.108(1)? (STDERR) Error: use "new" to construct a Mongo.Collection
W20150309-18:20:14.108(1)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:29:1)
W20150309-18:20:14.109(1)? (STDERR)     at new Ground.Collection (packages/ground:db/groundDB.server.js:80:1)
W20150309-18:20:14.109(1)? (STDERR)     at app/lib/collections.js:2:9
W20150309-18:20:14.109(1)? (STDERR)     at app/lib/collections.js:4:3
W20150309-18:20:14.109(1)? (STDERR)     at /home/alex/test/.meteor/local/build/programs/server/boot.js:205:10
W20150309-18:20:14.109(1)? (STDERR)     at Array.forEach (native)
W20150309-18:20:14.109(1)? (STDERR)     at Function._.each._.forEach (/home/alex/.meteor/packages/meteor-tool/.1.0.41.yumiah++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150309-18:20:14.109(1)? (STDERR)     at /home/alex/test/.meteor/local/build/programs/server/boot.js:116:5
=> Exited with code: 8
```

Perhaps I'm doing something wrong? Or should I open this bug with @GroundMeteor instead?

**Comment by msavin** [comment]
I was able to install GroundDB and it's working fine. Can you list your other packages, and send a copy of app/lib/collections.js?

**Comment by JackAdams** [comment]
Max, if @alexiri posts his `.packages` file, can you do the same with the `.packages` file from your app that works with grounddb.  I've got a suspicion about what's causing this and, if I'm right, there might be an easy fix.

**Comment by msavin** [comment]
I just added it to Mongol repo to see if there's any explicit issue. So it's pretty barebones.

**Comment by JackAdams** [comment]
Okay, that's easy.  I'll have a look at it later today.

**Comment by JackAdams** [comment]
Yep. Was able to reproduce the issue, but I don't think there's an easy fix from the Mongol end.

However, an app developer can get the packages to work together one of two different ways:

**1.** make sure `ground:db` is **after** `msavin:mongol` in the `.packages` file

**OR**

**2.** Define the collections as regular `Mongo.Collection` rather than `Ground.Collection` then ground them using something like: 

```
Posts = new Mongo.Collection("posts");
Ground.Collection(Posts);
```

**Comment by msavin** [comment]
That's fair - I think I'll just pop this into a "Compatibility" section of the documentation 

On Mar 09, 2015, at 08:46 PM, Brent Abrahams notifications@github.com wrote:

Yep. Was able to reproduce the issue, but I don't think there an easy fix from the Mongol end.
However, an app developer can get the packages to work together one of two different ways:
make sure ground:db is after msavin:mongol in the .packages file
OR
Define the collections as regular Mongo.Collection rather than Ground.Collection then ground them using something like:
Posts = new Mongo.Collection("posts"); Ground.Collection(Posts);

**Comment by alexiri** [comment]
I can confirm that placing `ground:db` after `msavin:mongol` worked. Thanks!

**Comment by JackAdams** [comment]
Thanks for the independent confirmation, Alex. Glad to hear it's working.

**Comment by msavin** [comment]
Awesome. I added this to compatibility post. 
https://github.com/msavin/Mongol/blob/master/COMPATIBILITY.md

PS: Make sure you run meteor update :)
