### ISSUE TITLE
mongol fails to load due to incompatibility with u2622:persistent-session

### ISSUE THREAD

**Issue by MichelFloyd** [msavin/Mongol#57]
Uncaught ReferenceError: EJSON is not defined reporters.js?1426735142249:67

Not sure who gets the blame here but I'm going to guess gwendall:session-json might be involved since it's a related package that's installed by mongol.

Found this during Max's presentation at tonight's South Bay Meteor meetup.

**Comment by JackAdams** [comment]
I think the problem is with u2622:persistent-session.  It [overwrites](https://github.com/okgrow/meteor-persistent-session/blob/master/lib/persistent_session.js) the `Session` functions, whereas gwendall:meteor-session-json just [updates](https://github.com/gwendall/meteor-session-json/blob/master/export.js) the `ReactiveVar` prototype.

However, this is the [most recent commit](https://github.com/okgrow/meteor-persistent-session/commit/bc34fc08b219d865611a944ff1d68865e9ffa768) for u2622:persistent-session, which may address the issue.

If that doesn't help, not sure that we can do much about this. (Except, maybe, give a config option to switch off the editable json.)

**Comment by krawalli** [comment]
"EJSON is not defined"

you need to api.use('ejson') in the package.js

**Comment by arvi** [comment]
I'm experiencing this too after adding _u2622:persistent-session_ package

`No collections found. If you think this is an error, please report it on Github.`

It's when I log-in to my app and CTRL+M, this would appear. However, if I did browser refresh at every page I navigate to, CTRL+M will list my subscriptions as expected.

Maybe this would be my workaround for now while this issue is still not resolved. :p

**Comment by JackAdams** [comment]
@krawalli -- is that in the `editable-json` `package.js` file?

**Comment by krawalli** [comment]
@JackAdams - its the message from the issue reporter in line 1 - Maybe its from your package.

**Comment by JackAdams** [comment]
Anyone got a minimal reproduction for this?  I couldn't reproduce it.

**Comment by JackAdams** [comment]
@msavin -- again, I'm pretty sure it's not the editable-json package that's causing this. It's possibly a conflict between the `u2622:persistent-session` and `gwendall:meteor-session-json` packages (the editable-json depends on the second package).  There's probably another package involved though, as I have both the above packages in a test app and no issues.

**Comment by msavin** [comment]
@MichelFloyd What I can recommend for now is installing the package manually and removing the editable JSON dependency. You may also have to set the hideInlineEditing helper to true. I'll look for a sturdier resolve in the future.

**Comment by MichelFloyd** [comment]
Thanks Max, I’ll give it a shot!

Congrats on quickly becoming one of the most popular packages for Meteor! Nice work!

**Comment by msavin** [comment]
@jackadams I understand that, but I don't understand why we need that package for Editable-JSON to work. It seems like it would be better to go without it for the sake of being leaner and preventing conflicts. 

@MichelFloyd Thanks man!

**Comment by msavin** [comment]
Closing this as it is technically not Mongol related
