### ISSUE TITLE
Windows 7(64bit) Chrome Browser Meteor windows (official version)

### ISSUE THREAD

**Issue by JS9** [msavin/Mongol#58]
I am new to the whole environment - so I may be missing something obvious. 
I get the message this app contains Mongol - however the app is not visible on screen.
Control + M does not work.
If I enter command to display mongol, it pops up on screen and says a collection not available. If this an error - report it on git hub.
So here is the report. 
Let me know if you need more info.

Thanks in advance - looks like a great utility.

**Comment by krawalli** [comment]
Please have a look at the package loading order.

Look into the .meteor/packages file.

Move the mongol entry to the top (e.g. line 2 or 3) and try again.

If mongol is added later on, its run to late to get notified on collection creation

**Comment by msavin** [comment]
@krawalli has anyone thought to just re-run the collection creation?

**Comment by krawalli** [comment]
yeah, but that's impossible. Its not the creation, its the javascript command to have a variable to represent collection XY.

Like:

``` javascript
MyCol = new Mongo.Collection('whatever');
```

With a collection hook on init (but must be implemented by MDG) that problem should be solved.

Another way would be to simply iterate over existing Collection instances on mongol init. Doing something like:

``` javascript
_.each(Mongo.Collection.listInstances(), function (collectionInstance) {
  // add its name to mongol
});
```

AFAIK there is nothing like that list instances.

So right now, mongol "should" be loaded as early as possible, since it extends the Mongo.Collection init call (something like a self created hook). Every code after mongol is loaded (as package) auto-informs mongol to add that collection to the list of collections.

**Comment by JS9** [comment]
Krawalli - Thank you - your suggestion worked. Here is the packages file.
Before when it wasn't working msavvvin:mongol was the last line - when I moved it after the meteor-platform - it started work. Thanks again for your quick help.

meteor-platform
msavin:mongol
autopublish
insecure

**Comment by JS9** [comment]
As my particular issue is fixed - I will close the thread.

**Comment by msavin** [comment]
Glad you got it working! Thanks @krawalli
