### ISSUE TITLE
Refresh on deletions

### ISSUE THREAD

**Issue by mastastealth** [msavin/Mongol#81]
When I have a collection of 10 items, and have the 10th item selected (10/10), if I run some code to remove, for example, 8 items, the tool shows 10/2, and I have to go backwards through all the non-existing items to get back to the last item (now 2/2).

It'd be nice if it could automatically adjust to the last item when something like this happens.

**Comment by msavin** [comment]
Thanks for the suggestion. It's implemented, along with 'looping' for arrow controls. Coming in Mongol 1.1 next week

**Comment by dpatte** [comment]
thx as well - noticed the same thing.

I love the community here! I 'discovered' meteor about 8 weeks ago, and have jumped in with both feet. I'm in the midst of converting a complete SaaS Drupal product into a Meteor product, and what took me 6 months to do before has been redone in only 6 weeks - not bad since I am learning as I am doing. My thanks go out to the community, the package developers like you and Jack Adams, and the Meteor team!

**Comment by msavin** [comment]
Folks, please update and me let know how its working

cc: @mastastealth 

@dpatte it's good :smile:
