### ISSUE TITLE
font-family of 'strong' tag

### ISSUE THREAD

**Issue by escaroda** [msavin/Mongol#99]
This appeared in my styles and broke my fonts (mongol v 1.1.0)

```
strong {
  font-weight: bold;
  font-family: Liberation Mono, Courier, Lucidatypewriter, Fixed, monospace !important;
}
```

**Comment by gabe-cabral** [comment]
Same here.

**Comment by Siyfion** [comment]
Agreed. Same here. This needs to be fixed asap.

@msavin This has broken people's lovingly crafted UI's! :cry:

**Comment by evolross** [comment]
Same here. +1

This error doesn't occur in `1.0.102`. So you can roll back using `meteor add msavin:mongol@=1.0.102`.  

With `1.1.0` I get the following CSS error in my console (looks like it has to do with `meteortoys:toykit`):

`downloadable font: rejected by sanitizer (font-family: "Liberation Mono" style:normal weight:bold stretch:normal src index:0) source: http://192.168.0.102:3000/packages/meteortoys_toykit/public/LiberationMono-Bold.ttf`

Love the tool tho. :) Please keep up the great work.

**Comment by EddyBorja** [comment]
+1

**Comment by msavin** [comment]
Hey folks, sorry for the delay in responding. I've been traveling, and I couldn't crack the issue because 1) it worked fine in Safari, my default browser, and 2) I had the font installed on my machine. However, Chrome gave it away and I pushed a fix as Mongol 1.1.1. Since its a patch update, it should go right into Meteor Toys as well. I've tested and there is no problem now, but if there is, please let me know.

**Comment by ghost** [comment]
It appears that the font decoding issue is gone.

However, it seems Mongol is still "hijacking" the styling for the < strong > tag (Chrome, Safari, Firefox). I think you want a more specific selector there.

**Comment by msavin** [comment]
Haha wow I can't believe I made such an amateur mistake. Corrected in 1.1.3

**Comment by ghost** [comment]
Hey no worries man! I do it all the time and I’ve been doing this a long time.

Thanks for the fix.

Chris

**Comment by gabe-cabral** [comment]
Thanks msavin!
